#!/bin/bash

if [[ -z $2 ]]; then
    FNPART="$RANDOM$RANDOM"
else
    FNPART="$2"
fi

NEWFN="notes/note-$(date +%Y%m%d)-$FNPART.tex"

sed "s|DATESTRING|$(date '+%Y-%m-%d')|" notes/.tmpl.tex > "$NEWFN"
